server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka
  instance:
    prefer-ip-address: true #以ip注册到注册中心
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
       git:
                uri: https://github.com/jenoves/aigou-config.git
                username: 137052045@qq.com
                password: daihao.47
